[package]
name = "rust-kanban"
version = "0.1.2"
authors = ["igor <ilaborie@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ilaborie/plop-tui"

[dependencies]
log = "0.4"
tui-logger = "0.8.1"
tui = "0.19.0"
crossterm = "0.25.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.23"
textwrap = "0.16"
eyre = "0.6"
home = "0.5.4"
serde = { version = "1.0.147", features = ["derive"]}
serde_json = "1.0.89"
diesel = "2.0.2"
clap = { version = "4.0.27", features = ["derive"] }
savefile-derive = "0.11.0"
savefile = "0.11.0"
uuid = { version = "1.2.2", features = ["v4"] }
either = "1.8.0"
