name: Build and Release

on:
  push:
    paths:
      - Cargo.toml
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r
    
    - name: Get version from cargo.toml
      run: |
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          env:
            version: $(Get-Content Cargo.toml | Select-String -Pattern 'version =' | Select-Object -First 1 | ForEach-Object { $_.ToString().Split(' ')[2].Trim('"') })
          echo "version=${{ env.version }}" >> $GITHUB_ENV
        else
          env:
            version: $(grep 'version =' Cargo.toml | awk '{print $3}' | tr -d '"')
          echo "version=${{ env.version }}" >> $GITHUB_ENV

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version from Cargo.toml
      run: |
        echo "version=$(sed -n 's/version = "\(.*\)"/\1/p' Cargo.toml | head -1)" >> $GITHUB_ENV

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: rust-kanban-windows-latest
        path: target/release/windows
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: rust-kanban-ubuntu-latest
        path: target/release/linux
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: rust-kanban-macos-latest
        path: target/release/macos

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.version }}"
        prerelease: true
        title: "Development Build"
        files: |
          target/release/windows/rust-kanban
          target/release/linux/rust-kanban
          target/release/macos/rust-kanban
