name: Linux build
on:
  push:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if the file Cargo.toml is changed
        $SourceDiff = $diff | Where-Object { $_ -match "Cargo.toml" }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "version_updated"
        Write-Host name=version_updated::$HasDiff >> $GITHUB_OUTPUT

    - name: Build
      if: steps.check_file_changed.outputs.version_updated
      run: cargo build -r

    - name: Get version from cargo.toml
      if: steps.check_file_changed.outputs.version_updated
      run: |
        #!/bin/bash
        echo "version=$(grep 'version =' Cargo.toml | awk '{print $3}' | tr -d '"' | head -1)" >> $GITHUB_ENV

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: steps.check_file_changed.outputs.version_updated
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.version }}" 
        prerelease: true
        title: "Development Build"
        files: |
          target/release/rust-kanban
      
