name: Linux build

on:
  push:
    paths:
      - Cargo.toml
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r
    - name: Get version from cargo.toml
      run: |
            #!/bin/bash
            echo "version=$(grep 'version =' Cargo.toml | awk '{print $3}' | tr -d '"' | head -1)" >> $GITHUB_ENV

    - name: Release on Windows, macOS, and Linux
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.version }}" 
        prerelease: true
        title: "Development Build"
        files: |
          target/release/rust-kanban*
      
